### ISSUE TITLE
bookmark generator not really working

### ISSUE THREAD

**Issue by mattetti** [al45tair/mac_alias#1]
Great job on the library and documentation. I needed to generate bookmarks programmatically and without linking to C. Unfortunately while this library is probably working super well to parse aliases and bookmarks, the generator didn't seem to work.
I took upon myself to reimplement the library in Go, I didn't focus on the parser but the generator and got it working: https://github.com/mattetti/cocoa 

I'm not a pythonista so I couldn't quite tell what's off or send a PR but I figured you might be interested. Anyways, thanks again for the great research work, that saved me hours and hours of work.

**Comment by al45tair** [comment]
Odd; it definitely works to generate bookmarks (we use this to build DMG images for distributing iDefrag and iPartition, and if bookmark generation didn't work, the background images wouldn't show up).

Also I note in your code you comment that the documentation is wrong in some respect; if you could elaborate I'd be much obliged :-)

**Comment by mattetti** [comment]
That's very odd indeed. I tried to generate a bookmark from random files on my hard drive and it wasn't working on macOs 10.12.6. At least I couldn't get it to work, even after figuring out how to set the xattr. But it might have been my fault.

When generating a bookmark locally using Finder's UI all my headers look like that:

```
00000000  62 6f 6f 6b 00 00 00 00  6d 61 72 6b 00 00 00 00  |book....mark....|
00000010  38 00 00 00 38 00 00 00  70 04 00 00 00 00 04 10  |8...8...p.......|
00000020  00 00 00 00 72 73 2f 6d  b8 3b 0b b3 b3 5b bf 41  |....rs/m.;...[.A|
00000030  00 00 00 00 63 65 2f 73
```
As can you see, the header size is 56 instead of 48 and the format is quite different from what you documented here: https://github.com/al45tair/mac_alias/blob/master/doc/bookmark_fmt.rst

The rest seemed to be on point with some slight differences when comparing my created vs generated files.

**Comment by mattetti** [comment]
I might have found the root cause of the generator issue. Are you by any chance generating the TOC by hand? Looking at https://github.com/al45tair/mac_alias/blob/master/mac_alias/bookmark.py#L627 the toc here is missing a CNID for the target and might be part of the issue.

**Comment by al45tair** [comment]
Ah, I think I see what the problem is here. You're talking about bookmark *files*, right, rather than just a bookmark *record*? The code in `mac_alias` was for generating the record format, not the file format; the two seem to be slightly different for some reason.

If you're saying that you've worked out what the differences are between the file and record formats, that would certainly be interesting and it'd be nice to support it in `mac_alias`.

**Comment by jakepetroules** [comment]
@al45tair Can you please update the bookmark documentation given the information on http://michaellynn.github.io/2015/10/24/apples-bookmarkdata-exposed/? i.e. "might" be a version is confirmed by debug output, size of header is actually an offset, etc.

@mattetti That looks like a Mac OS Alias file (i.e. right click > Make Alias), not a bookmark (they are different formats). A Mac OS Alias *file* is also not the same as Alias (v2) *resources* (which this module also reads/writes).

It seems that there's an *alternative* header for Alias records written to the filesystem, which is 56 bytes instead of 48, and is closely related to the bookmark format? (note that CFURLCreateBookmarkDataFromAliasRecord will convert between these)

- 16-byte magic ("book\0\0\0\0mark\0\0\0\0")
- 4-byte value ('56') - size of header*?
- 4-byte value ('56') - size of header checksum*?
- 4-byte value ('868') in my example with a 924-btye alias file, 924 - 56 = 868 so that must be the size of the alias data not including the header
- same 0x10040000 version value
- 24 reserved/garbage bytes?

... followed by the offset to the first TOC, relative to the end of the 56-byte header

**Comment by mattetti** [comment]
Ahhh that makes a lot of sense. Yes, I was trying to generate alias files containing the bookmark data and got it working (but Finder does change my file after loading it so I need to take a look at the delta to see what's up).

As mentioned and described above, the header is a bit different, a couple other keys are used and I noticed that the CNID path data comes before the offset (minor probably doesn't change anything based on how the TOC is read).

I am still confused by the crazy amount of alias formats and how the header might different when used in.memory vs on a volume, but it was a fun exercise. Speaking of which, the finder flag attrx must be set so the file can be seen as an Alias by Finder.
